CREATE TABLE order (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    status order_status NOT NULL,
    totalPrice INT NOT NULL CHECK ( total_price >= 0 ),
    deleted order_status NOT NULL
);

CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE